### ISSUE TITLE
中間発表

### ISSUE THREAD

**Issue by taikit** [taikit/Nemo#19]
中間発表で共通している点
書かなければいけない項目

**Comment by ghost** [comment]
参考資料

![img_1834](https://cloud.githubusercontent.com/assets/15015847/10629144/4c80552c-7807-11e5-8924-3a00a12502fc.JPG)
![img_1835](https://cloud.githubusercontent.com/assets/15015847/10629146/4c84f438-7807-11e5-8492-1138e98c2663.JPG)
![img_1836](https://cloud.githubusercontent.com/assets/15015847/10629145/4c83d5a8-7807-11e5-83ed-7405cc30584e.JPG)
![img_1837](https://cloud.githubusercontent.com/assets/15015847/10629147/4c85dca4-7807-11e5-8e53-740125a7940b.JPG)
![img_1838](https://cloud.githubusercontent.com/assets/15015847/10629148/4c88fdb2-7807-11e5-983f-215c2b894231.JPG)
![img_1839](https://cloud.githubusercontent.com/assets/15015847/10629150/4ca3e6c2-7807-11e5-9072-e632800cdee3.JPG)
![img_1840](https://cloud.githubusercontent.com/assets/15015847/10629149/4ca3ae3c-7807-11e5-8859-5ff6258edc37.JPG)
![img_1841](https://cloud.githubusercontent.com/assets/15015847/10629151/4ca5115a-7807-11e5-9925-477898a5a5bf.JPG)
![img_1842](https://cloud.githubusercontent.com/assets/15015847/10629152/4ca678ba-7807-11e5-98b5-676679b441c5.JPG)
![img_1843](https://cloud.githubusercontent.com/assets/15015847/10629153/4ca9141c-7807-11e5-8477-fdd20a99adf4.JPG)
![img_1844](https://cloud.githubusercontent.com/assets/15015847/10629154/4cac5744-7807-11e5-9a8d-64a4fd990b53.JPG)
![img_1845](https://cloud.githubusercontent.com/assets/15015847/10629143/4c7c9392-7807-11e5-954b-833bcb46128c.JPG)

**Comment by ghost** [comment]
中間発表の共通部分
https://docs.google.com/document/d/1DW-kM8_G_zLxtdQMeHLaDYYi6jkJ19apkad6Iy85xw0/edit?usp=sharing

**Comment by taikit** [comment]
[実験D中間発表プレゼン資料.pptx](https://github.com/taikit/Nemo/files/21526/D.pptx)
