### ISSUE TITLE
ペーパープロトタイプ

### ISSUE THREAD

**Issue by taikit** [taikit/Nemo#8]

**Comment by shu-taka** [comment]
![img_1817](https://cloud.githubusercontent.com/assets/15015847/10629069/bfab9026-7806-11e5-9d56-1f75a3b1a523.JPG)
![img_1818](https://cloud.githubusercontent.com/assets/15015847/10629068/bfaa6b9c-7806-11e5-9921-81033b2d59b8.JPG)
![img_1819](https://cloud.githubusercontent.com/assets/15015847/10629070/bfabc186-7806-11e5-8724-95f4cbefc5ae.JPG)
![Uploading IMG_1820.JPG…]()
![Uploading IMG_1821.JPG…]()

**Comment by ghost** [comment]
![img_1817](https://cloud.githubusercontent.com/assets/15015847/10629090/e3c2ed74-7806-11e5-9225-92e7d28256d1.JPG)
![img_1818](https://cloud.githubusercontent.com/assets/15015847/10629091/e3c37ea6-7806-11e5-9491-9ab9974c345c.JPG)
![img_1819](https://cloud.githubusercontent.com/assets/15015847/10629092/e3caced6-7806-11e5-86c6-2b538d835c3a.JPG)
![img_1820](https://cloud.githubusercontent.com/assets/15015847/10629093/e3cc1f70-7806-11e5-97f4-1d956cc41982.JPG)
![img_1821](https://cloud.githubusercontent.com/assets/15015847/10629094/e3cd92ce-7806-11e5-9223-07016bdc89b0.JPG)
